### PR TITLE
Feature/interview optimisation

### PR DESCRIPTION
**Pull request by JesseCr00**
Naming refactor, and link to frontend.
Needs to be tested before PR opened for review

### CODE REVIEW

**Comment by JesseCr00** [comment]
Needs to be tested

**Comment by JesseCr00** [comment]
Working for Local Testing now. Will create new branch when it gets fixed for prod deployment

**Review by Khang0018 — APPROVED** [review]
LGTM

**Review by Tavishi11 — APPROVED** [review]
Looks good to me
Tested on my mac.

**Pull request merged**
