### PR TITLE
Added All Contributors bot

### PR DESCRIPTION
**Pull request by arazzell**

### CODE REVIEW

**Comment by arazzell** [comment]
@all-contributors
please add @ahmadhafiz17 for Team Member. 
please add @Fahad Assadi for Team Member.
please add @Jesse Cruickshank for Team Member.
please add @Khang0018 for Team Member.
please add @NgoTranNgocDuy for Team Member.
please add @Rahul-Saxena-1 for Team Member.
please add @Rahuls525 for Team Member.
please add @Ranith1 for Team Member.
please add @sai-ramishetty for Team Member.
please add @Shubh Bajpai Team Member.
please add @Tavishi11Team Member.
please add @Umair Bin Mohammad for Team Member.

**Comment by arazzell** [comment]
@all-contributors
please add @ahmadhafiz17 for Team Member.
please add @FahadAssadi for Team Member.
please add @jcru0005 for Team Member.
please add @Khang0018 for Team Member.
please add @NgoTranNgocDuy for Team Member.
please add @Rahul-Saxena-1 for Team Member.
please add @Rahuls525 for Team Member.
please add @Ranith1 for Team Member.
please add @sai-ramishetty for Team Member.
please add @shubh Bajpai Team Member.
please add @Tavishi11 Team Member.
please add @umairBinMohammad for Team Member.
please add @arazzell for Team Member.
please add @HanifZafari for Team Member.
please add @brendonPerera for Team Member.

**Comment by arazzell** [comment]
https://github.com/all-contributors
please add @ahmadhafiz17 for code.
please add @FahadAssadi for code.
please add @jcru0005 for code.
please add @Khang0018 for code.
please add @NgoTranNgocDuy for code.
please add @Rahul-Saxena-1 for code.
please add @Rahuls525 for code.
please add @Ranith1 for code.
please add @sai-ramishetty for code.
please add @ShubhBajpai25 for code.
please add @Tavishi11 for code.
please add @umairBinMohammad for code.
please add @arazzell for code.
please add @HanifZafari for code.
please add @brendonPerera for code.

**Comment by arazzell** [comment]
@all-contributors
please add @ahmadhafiz17 for code.
please add @FahadAssadi for code.
please add @jcru0005 for code.
please add @Khang0018 for code.
please add @NgoTranNgocDuy for code.
please add @Rahul-Saxena-1 for code.
please add @Rahuls525 for code.
please add @Ranith1 for code.
please add @sai-ramishetty for code.
please add @ShubhBajpai25 for code.
please add @Tavishi11 for code.
please add @umairBinMohammad for code.
please add @arazzell for code.
please add @HanifZafari for code.
please add @brendonPerera for code.

**Review by JesseCr00 — APPROVED** [review]
Looks good, cheers for implementing this!

**Comment by umairBinMohammad** [comment]
Looks good, good bot.

**Review by Rahul-Saxena-1 — APPROVED** [review]

**Comment by arazzell** [comment]
https://github.com/all-contributors
please add @ahmadhafiz17 for code.
please add @FahadAssadi for code.
please add @jcru0005 for code.
please add @Khang0018 for code.
please add @NgoTranNgocDuy for code.
please add @Rahul-Saxena-1 for code.
please add @Rahuls525 for code.
please add @Ranith1 for code.
please add @sai-ramishetty for code.
please add @ShubhBajpai25 for code.
please add @Tavishi11 for code.
please add @umairBinMohammad for code.
please add @arazzell for code.
please add @HanifZafari for code.
please add @brendonPerera for code.

**Comment by arazzell** [comment]
@all-contributors
please add @ahmadhafiz17 for code.
please add @FahadAssadi for code.
please add @jcru0005 for code.
please add @Khang0018 for code.
please add @NgoTranNgocDuy for code.
please add @Rahul-Saxena-1 for code.
please add @Rahuls525 for code.
please add @Ranith1 for code.
please add @sai-ramishetty for code.
please add @ShubhBajpai25 for code.
please add @Tavishi11 for code.
please add @umairBinMohammad for code.
please add @arazzell for code.
please add @HanifZafari for code.
please add @brendonPerera for code.

**Pull request merged**
